### ISSUE TITLE
🎉 Enable to submit todo from independent modal

### ISSUE THREAD

**Issue by aNobuhisaMasaki** [diescake/igata#263]

**Comment by aNobuhisaMasaki** [comment]
@diescake @KensukeTakahara @aTakatoNakamura
Already implemented an embedded version in a fork:
https://github.com/aTakatoNakamura/igata/pull/1
For independent component in progress...

**Comment by aNobuhisaMasaki** [comment]
PR in https://github.com/diescake/igata/pull/266 .

**Comment by diescake** [comment]
merged ! 🎉
