### ISSUE TITLE
🚀 How about to make tag for release?

### ISSUE THREAD

**Issue by pankona** [diescake/igata#308]
It seems there's not release tag yet.
Release tag helps us to understand the recent updates and differences between previous version. How about to make it? 😋

**Comment by diescake** [comment]
Hey, :rocket:

**Comment by pankona** [comment]
Great! 🚀

**Comment by diescake** [comment]
Hi, @pankona ! Thanks for your great suggestion !! 🚀
I created the [release tag v0.10](https://github.com/diescake/igata/releases/tag/v0.10) right now.

However, there is one problem. How can I use template from the release tag ? 👽

**Comment by diescake** [comment]
I recreated the [new release](https://github.com/diescake/igata/releases/tag/v0.1.0) because former tag is not based on a semantic versioning. 🚀 
Unfortunately, we can only use template from HEAD of default branch for now.
